# Alpine
FROM mcr.microsoft.com/dotnet/sdk:6.0-alpine AS build
WORKDIR /app
COPY doctrack .

RUN dotnet publish -r linux-x64 -c Release -o /app/publish /p:PublishSingleFile=true

FROM mcr.microsoft.com/dotnet/aspnet:6.0-alpine

WORKDIR /app
COPY --from=build /app/publish .
# COPY doctrack_template.docx .

# CMD ["node", "index.js"]
CMD ["tail", "-f", "/dev/null"]